# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  root_path = "../"
  artifacts_directory = "artifacts"
  artifacts_path = root_path + artifacts_directory
  upload_script = "upload-dsyms.sh"
  min_version_filepath = root_path + "min_version.txt"
  options_plist_path = "options.plist"

  lane :refresh_dsyms do
    clean_artifacts_directory
    options = get_download_options
    download_artifacts(options: options)
    # sh_upload_dsyms
    # clean_build_artifacts
  end

  private_lane :clean_artifacts_directory do
    sh("rm -rf " + artifacts_path)
    sh("mkdir " + artifacts_path)
  end

  private_lane :get_download_options do
    if ENV["CI"] == 1 then
      key = get_info_plist_value(path: options_plist_path, key: "ci_key")
      {
        version: ENV[key + "_VERSION"],
        min_version: ENV[key + "_MIN_VERSION"],
        after_uploaded_date: ENV[key + "_AFTER_UPLOAD_DATE"]
      }
    else 
      {
        version: get_info_plist_value(path: options_plist_path, key: "version"),
        min_version: get_info_plist_value(path: options_plist_path, key: "min_version"),
        after_uploaded_date: get_info_plist_value(path: options_plist_path, key: "after_uploaded_date")
      }
    end
  end

  private_lane :download_artifacts do |parameters|
    options = parameters[:options]
    version = options[:version]
    min_version = options[:min_version]
    after_uploaded_date = options[:after_uploaded_date]
    if !version.nil? then 
      # download_dsyms(version: version, output_directory: artifacts_directory)
      puts("version " + version)
    elsif !min_version.nil? then 
      # download_dsyms(min_version: min_version, output_directory: artifacts_directory)
      puts("min_version " + min_version)
    elsif !after_uploaded_date.nil? then 
      # download_dsyms(after_uploaded_date: after_uploaded_date, output_directory: artifacts_directory)
      puts("after_uploaded_date " + after_uploaded_date)
    else
      # download_dsyms(output_directory: artifacts_directory)
      puts("all ")
    end
  end

  private_lane :sh_upload_dsyms do
    sh("sh -x " + root_path + upload_script + " " + artifacts_path)
  end

  private_lane :get_min_version do
    File.read(min_version_filepath)
  end

end
