# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  root_path = "../"
  artifacts_directory = "artifacts"
  upload_script = "upload-dsyms.sh"
  min_version_filepath = "../min_version.txt"

  lane :refresh_dsyms do
    min_version = get_min_version
    sh("rm -rf " + root_path + artifacts_directory)
    sh("mkdir " + root_path + artifacts_directory)
    download_dsyms(version: min_version, output_directory: artifacts_directory)
    # download_dsyms(version: "1.0.0", output_directory: artifacts_directory)
    # download_dsyms(after_uploaded_date: "2021-02-01T21:02:01+01:00", output_directory: artifacts_directory)
    sh("sh -x " + root_path + upload_script + " " + root_path + artifacts_directory)
    clean_build_artifacts
  end

  private_lane :get_min_version do
    File.read(min_version_filepath)
  end

end
